### ISSUE TITLE
Class 'PathBase' incorrectly implements class 'Dirent'.

### ISSUE THREAD

**Issue by jcesarmobile** [isaacs/path-walker#13]
Note that I don't use path-scurry directly but some dependency is using it and now it's breaking our build with this message:

```
../node_modules/path-scurry/dist/cjs/index.d.ts:116:31 - error TS2720: Class 'PathBase' incorrectly implements class 'Dirent'. Did you mean to extend 'Dirent' and inherit its members as a subclass?
  Property 'path' is missing in type 'PathBase' but required in type 'Dirent'.

116 export declare abstract class PathBase implements Dirent {

Found 1 error in ../node_modules/path-scurry/dist/cjs/index.d.ts:116
```

**Comment by isaacs** [comment]
What version of node and @types/node do you have? fs.Dirent definitely does not have a `path` member, so that's weird.

**Comment by jcesarmobile** [comment]
In my computer I've used node 16, on the CI node 18.
I don't pin a specific @types/node version, but looks like 20.1.3 is being installed because of other dependencies.

pinning ^18.16.8 solves the issue, so not sure if it's a problem on @types/node 20.x or if your package will break in node 20. 
Feel free to close if you think the problem is in @types/node and I'll report the problem there.

**Comment by pilafmon** [comment]
The incompatibility looks to have been introduced with **@types/node** `20.1.3` and is still present in `20.1.4` (latest version at this time). The older **@types/node** `20.1.2` appears to be fine.

```bash
% npm list @types/node    
replacer-util@1.0.2 /Users/dem/projects/replacer-util
├─┬ @types/glob@8.1.0
│ └── @types/node@20.1.3 deduped
└── @types/node@20.1.3
```

**Comment by isaacs** [comment]
Ah, indeed, the `Dirent['path']` was added in node 20, refering to the path that was read to get the directory entries.  I can update the PathBase class to include that, probably. It's a bit counterintuitive for `Path.path` to refer to `Path.parent.fullpath()` though, might be better to just explicitly extend `Omit<Dirent, 'path'>`.

**Comment by isaacs** [comment]
Decided to just go ahead and add the same property, so you can use Path objects wherever you have Dirents, and make a note in the tsdoc re the weirdness of the property.

**Comment by isaacs** [comment]
I guess it's not quite 100% identical, since `readdir('.')` will give you Dirents with a `path` of `'.'`, but path-scurry Path objects will always have `path` set to the full absolute path, but it's close enough for any reasonable purposes, probably.
