### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ukhanzada-nisum-com** [isaacs/path-walker#15]
I am facing an issue while trying to upload the source map on Sentry.. I'm doing this with Manually Setup with Webpack and I am using Sentry's recommended plugin "@sentry/webpack-plugin" but the issue is when I'm loading/importing this plugin in Webpack config I'm getting the below error. 

const { sentryWebpackPlugin } = require('@sentry/webpack-plugin'); // if I remove this line it's working fine.

node_modules/path-scurry/dist/cjs/index.js:363
    #resolveParts(dirParts) {
                 ^
SyntaxError: Unexpected token '('

node: 14,
webpack: 4.44.2,
@sentry/react: 7.52.1,
@sentry/webpack-plugin: 2.5.0,
react and typescript

**Comment by isaacs** [comment]
Looks like your webpack version (or the version of node in use) doesn't support private class property syntax. I'm not familiar with sentry, but this looks like an issue with the js parser in use.

Out of curiosity, why are you bundling path-scurry for the browser? It's very node and file system specific. Seems like it won't be much good on a browser, and will bloat the bundle size considerably.

**Comment by ukhanzada-nisum-com** [comment]
path-scurry is a peer dependency.. I'm not using it, it's used by some internal modules moreover I have tried updating Webpack, Node, and also used `@babel/plugin-transform-private-methods`  plugin but didn't work.
<img width="1123" alt="private-class-error" src="https://github.com/isaacs/path-scurry/assets/38420106/16a7d86e-8767-4eac-b370-bf6fed560ef7">

**Comment by isaacs** [comment]
This looks like it is happening in Module._compile. Are you quite sure you're on node 14.latest? Add a `console.log(process.version)` in the program that's crashing.

**Comment by ukhanzada-nisum-com** [comment]
Yes, 14.0.0

**Comment by isaacs** [comment]
That is not 14.latest.  The requirement is `14 >=14.17`, so you need to be on 14.17.0 at least.
