### ISSUE TITLE
Class 'PathBase' incorrectly implements class 'Dirent' (again)

### ISSUE THREAD

**Issue by mrginglymus** [isaacs/path-walker#18]
As with https://github.com/isaacs/path-scurry/issues/13, except this time it's [`parentPath`](https://nodejs.org/docs/latest-v20.x/api/fs.html#direntparentpath), `path` having been deprecated.

As of @types/node 20.12.11 (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69490)

**Comment by philkunz** [comment]
Same problem here.

**Comment by philkunz** [comment]
Pinning @types/node to [20.10.0](https://www.npmjs.com/package/@types/node/v/20.10.0) fixes the issue for now.

**Comment by cipherdmg** [comment]
I looked yesterday here since I hit this problem a few days ago since I updated my nodejs and types package.  I patched the index.d.ts to include the missing getter and it resolved it but I think downgrading nodejs types is cleaner.

Once the update is released I will switch over.

Thanks
CipherDMG

**Comment by leahecole** [comment]
It looks like the [1.10.4 release](https://github.com/isaacs/path-scurry/releases/tag/v1.10.4) from a little while ago fixed this for me 🥳 , thanks folks!

**Comment by cipherdmg** [comment]
Thanks for patching the release.  This is now fixed for me.
