### ISSUE TITLE
Class 'PathBase' incorrectly implements class 'Dirent'.

### ISSUE THREAD

**Issue by arthurfiorette** [isaacs/path-walker#22]
When upgrading @types/node from 20.12.7 to 20.12.12, some types in this library starts to break.

More info at:
https://github.com/vega/ts-json-schema-generator/actions/runs/9242613488/job/25425656701?pr=1973#step:6:11

**Comment by isaacs** [comment]
`parentPath` is implemented as of version 1.10.3. Please upgrade.

**Comment by isaacs** [comment]
a1241ff
