### ISSUE TITLE
License file name doesn't get autobundled with existing libraries due to webpack extension filtering.

### ISSUE THREAD

**Issue by kcarrillorhoads** [isaacs/path-walker#23]
The existing pattern for this kind of licenses it to have the license be named LICENSE or LICENSE.txt not LICENSE.md

This naming pattern breaks tooling which auto posts the license as part of the Node code.

**Comment by isaacs** [comment]
No, the canonical name to use for a license such as BlueOak which is in markdown is LICENSE.md.

If node is shipping this code without the license, then that's a problem. I'll look into it. If that's the case, then they have 30 days to rectify the situation, or else lose their right to use the code.

**Comment by isaacs** [comment]
@Nodejs Can someone comment on this? No anger or drama from my point of view, I'm sure it's an honest mistake if so, but if path-scurry (and probably glob as well?) is being distributed without the license, then that's a problem.

**Comment by isaacs** [comment]
As far as I can tell, Node is only using glob and path-scurry internally, not as part of the deployment. And the internal usage has the `LICENSE.md` alongside the code, so I think everything's above board. Apologies if the ping disturbed anyone.

If it does end up being part of the actual deployment though, then the license will have to be included.

**Comment by kcarrillorhoads** [comment]
With all due respect webpack plugin is what people use and Webpack only will concatenate LICENSE.txt and LICENSE files leaving out the .md files.  Repo here: https://github.com/codepunkt/webpack-license-plugin
The Blue Oak License by definition needs to be posted and displayed with the front end, and to accomplish that one use case is Webpack.  If you are fulfilling this with another utility we can refactor but webpack continues to work for all but your library.

**Comment by bdumford-OM1** [comment]
We are experiencing this issue because we have `@aws-amplify/ui` as a dependency.  The dependency tree is @aws-amplify/ui -> style-dictionary -> glob -> path-scurry.  As far as I can tell, it's packaging `path-scurry` in with it.  However, webpack won't pull the license since it's a `.md`.

**Comment by kcarrillorhoads** [comment]
@isaacs Sorry to pull you back to this but I think that nuance might have been missing before because WebPack is the library of choice to fulfill the license guidelines here:
**Notices
You must ensure that everyone who gets a copy of any part of this software from you, with or without changes, also gets the text of this license or a link to https://blueoakcouncil.org/license/1.0.0.**

Webpack will do the license concatenation of all dependencies but only puts LICENSE and LICENSE.txt files into that concatenation.

**Comment by isaacs** [comment]
That's a webpack issue, and a serious one. Many licenses in the npm registry use `LICENSE.md` (or even `LISENSE.*` or `LICENCE.*`) as the filename.

Fix it in webpack. Not here.

**Comment by kcarrillorhoads** [comment]
Do they include the clause about text of license though? Your unique case is the use of a license that requires distribution of the license text.

Famously the MIT or GPL 2.0 licenses are usually packaged in files named LICENSE.txt or LICENSE but also don't have explicit language about packaging the license text as part of the license.

**Comment by isaacs** [comment]
> don't have explicit language about packaging the license text as part of the license.

That is 100% incorrect.

The MIT license: 

> **The above copyright notice and this permission notice shall be included** in all copies or substantial portions of the Software.

All BSD license variants:

> 1. Redistributions of source code **must retain the above copyright notice, this list of conditions and the following disclaimer.**

The ISC license:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, **provided that the above copyright notice and this permission notice appear in all copies**.

The Zlib License phrases it as a double-negative, but with the same meaning:

> This notice **may not be removed or altered from any source distribution.**

Artistic 2.0 says:

> You may Distribute verbatim copies of the Source form of the Standard Version of this Package in any medium without restriction, either gratis or for a Distributor Fee, **provided that you duplicate all of the original copyright notices and associated disclaimers.**

The list goes on and on. Pretty much all liberal non-copyleft open source licenses require that you distribute the license text with any copy of the source code.

In fact, BlueOak is quite a bit _more_ liberal than most, as you can provide recipients of the software with a link to the license rather than the license text itself.
