### ISSUE TITLE
Please revert the `lru-cache` update, it is a breaking change

### ISSUE THREAD

**Issue by romainmenke** [isaacs/path-walker#9]
https://github.com/isaacs/path-scurry/blob/3cee97c9842dd2548b741dfaa8605fc0fcc9bd78/package.json#L84

This is a breaking change that was released in a patch update.
Please revert this, it broke all our projects that still need to support node 14 :/

It also conflicts with : https://github.com/isaacs/path-scurry/blob/main/package.json#L74

**Comment by isaacs** [comment]
I'll patch LRUCache to support node 14 again. The only way is forward.

**Comment by isaacs** [comment]
I need to move all my cjs/esm hybrid projects to not use default exports.

**Comment by isaacs** [comment]
LRUCache now ships with an AbortController polyfill, so it works as of 9.0.1.

**Comment by romainmenke** [comment]
Thank you for the speedy fix!

**Comment by isaacs** [comment]
It is a bit noisy on node 14, so if you're using it there you may want to pull in the module it suggests, which is a much more comprehensive polyfill.

**Comment by romainmenke** [comment]
Thanks for the heads up!
